Repository GSG-FC02/API-A.Sabbah-Ibrahim, pull requests merged in 2021-04, with the labels that each got.

#2 all Files of the code of joke Api
  .vscode/settings.json
  index.html
  script.js
  style.css
Labels: in-progress

#4 updating the readme file
  README.md
Labels: Done

#10 style changes
  style.css
Labels: awaiting-review

#12 puting the display code inside the fetch
  script.js
Labels: awaiting-review
